# not working!

services:
  fsharpmajor:
    image: kamiyo/fsharpmajor:development
    env_file:
      - .env
    network_mode: service:db
    ports:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
  migration:
    image: ghcr.io/amacneil/dbmate
    depends_on:
      db:
        condition: service_healthy
    network_mode: service:db
    env_file:
      - .env
    
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -d ${DATABASE_URL}'"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres-data:
    driver: local