version: '3.8'

services:
  fsharpmajor:
    image: kamiyo/fsharpmajor:development
    env_file:
      - .env
    network_mode: service:db
    ports:
      - "8080"
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres-data:
    driver: local