version: '3.8'

services:
  fsharpmajor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    env_file:
      - .env
    command: sleep infinity
    network_mode: service:db
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres-data:
    driver: local